name: Java CI with Maven / CMake

on:
  push:
    branches: [ 'master', 'restructure-components' ]
  pull_request:
    branches: [ 'master', 'restructure-components' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      # Run MDE Workflow
      - name: Process MDE workflow with Maven
        run: mvn clean install --file pom.xml

      # Build and test Java Framework
      - name: Build Java Framework
        run: mvn -Dmaven.javadoc.skip=true -B install --file de.unistuttgart.iste.sqa.mpw.framework.java/pom.xml

      # Build and test C++ Framework
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.5
        with:
          cmake-version: '3.17.x'
      - name: Build C++ Framework
        run: cmake -S $PROJECT_CPP_DIR -B $BUILD_DIR && cmake --build $BUILD_DIR && cd $BUILD_DIR && ctest --extra-verbose
        env:
          PROJECT_CPP_DIR: de.unistuttgart.iste.sqa.mpw.framework.cpp
          BUILD_DIR: de.unistuttgart.iste.sqa.mpw.framework.cpp/build

