name: Java CI with Maven / CMake

on:
  push:
    branches: [ 'master', 'review-2021-02' ]
  pull_request:
    branches: [ 'master', 'review-2021-02' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15

      # Run MDE Workflow
      - name: Process MDE workflow with Maven
        run: mvn clean install --file pom.xml

      # Build and test Java Framework
      - name: Build Java Framework
        run: mvn -Dmaven.javadoc.skip=true -B package --file simulators/de.unistuttgart.iste.sqa.mpw.framework.java/pom.xml
        env:
          SNAPSHOT_REPOSITORY_URL: file:///${HOME}/deploy-java-framework-to-branch/repository

      # Build and test C++ Framework
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.5
        with:
          cmake-version: '3.17.x'
      - name: Build C++ Framework
        run: cmake -S $PROJECT_CPP_DIR -B $BUILD_DIR && cmake --build $BUILD_DIR && cd $BUILD_DIR && ctest --extra-verbose
        env:
          PROJECT_CPP_DIR: simulators/de.unistuttgart.iste.sqa.mpw.framework.cpp
          BUILD_DIR: simulators/de.unistuttgart.iste.sqa.mpw.framework.cpp/build
