name: Java CI with Maven

on:
  push:
    branches: [ 'github-ci' ]
  pull_request:
    branches: [ 'github-ci' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with Maven
        run: mvn clean package --file pom.xml
      - name: Built Java Simulator
        run: mvn -Dmaven.javadoc.skip=true -B package --file de.unistuttgart.iste.sqa.mpw.hamstersimulator.java/pom.xml