name: Java CI with Maven

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      # Run MDE Workflow
      - name: Process MDE workflow with Maven
        run: mvn clean package --file pom.xml

      # Build and test Java Simulator
      - name: Build Java Simulator
        run: mvn -Dmaven.javadoc.skip=true -B package --file de.unistuttgart.iste.sqa.mpw.hamstersimulator.java/pom.xml

      # Build and test C++ Simulator
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.5
        with:
          cmake-version: '3.17.x'
      - name: Build C++ Simulator
        run: cmake -S $SIMULATOR_CPP_DIR -B $BUILD_DIR && cmake --build $BUILD_DIR && cd $BUILD_DIR && ctest --extra-verbose
        env:
          SIMULATOR_CPP_DIR: de.unistuttgart.iste.sqa.mpw.hamstersimulator.cpp
          BUILD_DIR: de.unistuttgart.iste.sqa.mpw.hamstersimulator.cpp/build

